### ISSUE TITLE
React/RCTEventEmitter.h' file not found (react-native)

### ISSUE THREAD

**Issue by gulsher7** [hypertrack/sdk-react-native#13]
After successfully integrated this package for android i'm facing issue in iOs..I spent almost 4 hours to find out the solution.Its very painful to integrate sdk for ios. i followed the all setup to integrate this sdk for ios.. Please help me.. Please look into images which i mention below...

![Screenshot 2020-10-03 at 9 39 32 PM](https://user-images.githubusercontent.com/56266123/94996314-8bf75000-05c1-11eb-97a6-dff25982e6dc.png)
![Screenshot 2020-10-03 at 9 38 50 PM](https://user-images.githubusercontent.com/56266123/94996326-a6312e00-05c1-11eb-855e-397a45ee847c.png)

**Comment by DmitryShapovalov** [comment]
@gulsher7 Hello, which version of react-native do you use in that project ?

**Comment by gulsher7** [comment]
latest version 0.63.3

**Comment by DmitryShapovalov** [comment]
@gulsher7 This issue is due to the use `use_framework!` in the podfile, our integration documentation is out of date, i am working on updating it. I think it will work in a few days. Thanks and apologies for waiting.

Similar integration issue: https://github.com/hypertrack/sdk-react-native/issues/14

**Comment by gulsher7** [comment]
> @gulsher7 This issue is due to the use `use_framework!` in the podfile, our integration documentation is out of date, i am working on updating it. I think it will work in a few days. Thanks and apologies for waiting.
> 
> Similar integration issue: #14

please fix this bug asap..i'm working on client project and client is angry because i'm unable to work further..and before upload latest code on github please ensure that this sdk proper working on android or ios devices..it's huge humble request to you.

**Comment by DmitryShapovalov** [comment]
@gulsher7 Im working on it now, will notify you when new release will be available.

**Comment by DmitryShapovalov** [comment]
@gulsher7 I'm fixed that issue in the new release `7.0.1`, please use that release to resolve your issue. The integration [guide](https://www.hypertrack.com/docs/install-sdk-react-native) was updated as well due to up react-native version to 0.63.3. Android/iOS wrappers tested and ready to use. 

Please, Please let me know if everything works for you.

**Comment by DmitryShapovalov** [comment]
I am closing this issue because the problem has been resolved, if you have any difficulties with react-native, please contact us or create a new issue.
FYI @gulsher7
